### ISSUE TITLE
Error when trying to run flip commands

### ISSUE THREAD

**Issue by kevinold** [voodootikigod/node-rolling-spider#43]
On latest master (1.2.1) I receive the following error when issuing a flip command from eg/keyboard.js. 

Below is the output:

Configured for Rolling Spider!  RS_R107537
ready for flight
takeoff
takeoff
takeoff

/Users/kold/github_clones/node-rolling-spider/node_modules/noble/lib/characteristic.js:60
      callback(null);
      ^
TypeError: object is not a function
    at Characteristic.<anonymous> (/Users/kold/github_clones/node-rolling-spider/node_modules/noble/lib/characteristic.js:60:7)
    at Characteristic.g (events.js:180:16)
    at Characteristic.emit (events.js:92:17)
    at Noble.onWrite (/Users/kold/github_clones/node-rolling-spider/node_modules/noble/lib/noble.js:279:20)
    at emit (events.js:106:17)
    at nobleBindings.write (/Users/kold/github_clones/node-rolling-spider/node_modules/noble/lib/mac/yosemite.js:550:10)
    at Noble.write (/Users/kold/github_clones/node-rolling-spider/node_modules/noble/lib/noble.js:272:19)
    at Characteristic.write (/Users/kold/github_clones/node-rolling-spider/node_modules/noble/lib/characteristic.js:64:15)
    at Drone.writeTo (/Users/kold/github_clones/node-rolling-spider/lib/drone.js:342:49)
    at frontFlip (/Users/kold/github_clones/node-rolling-spider/lib/drone.js:605:10)

**Comment by voodootikigod** [comment]
This appears to be a noble issue more than rolling spider -- its calling the callback before checking if the provided callback is valid.

**Comment by kevinold** [comment]
Indeed. I filed here for context and meant to circle back yesterday to clarify what you've mentioned and cc @sandeepmistry

**Comment by voodootikigod** [comment]
Can you try with 1.3.0 I think I found the bug in my side... possibly or another bug that would have come out later ;)

**Comment by kevinold** [comment]
Yeah that patch looks like it will work. I was headed in that direction yesterday but was managing a frustrated 4 year old upset because it didn't flip ;) Will give it a try this afternoon.   

On June 14, 2015 at 8:48:16 AM CDT, Chris Williams notifications@github.com wrote:Can you try with 1.3.0 I think I found the bug in my side... possibly or another bug that would have come out later ;)  —Reply to this email directly or view it on GitHub.

**Comment by voodootikigod** [comment]
also if you have a logitech f310 hanging around check out `eg/gamepad.js` ;)

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.
