### ISSUE TITLE
Problem at 'npm install rolling-spider'

### ISSUE THREAD

**Issue by ChangkiSung** [voodootikigod/node-rolling-spider#98]
I have node version as v6.11.1 and ubuntu 4.8.

But, if i do 'npm install rolling-spider' on terminal, I get these errors

Anyone knows why it happened ?
```
npm WARN deprecated node-hid@0.4.1: bad semver, NANv2 change means we shoudl be v0.5.0, NANv1 is 0.4.0

> node-hid@0.4.1 install /home/himadri/node_modules/logitech-dual-action-controller/node_modules/node-hid
> node-gyp rebuild

make: Entering directory '/home/himadri/node_modules/logitech-dual-action-controller/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
compilation terminated.
hidapi.target.mk:97: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
make: Leaving directory '/home/himadri/node_modules/logitech-dual-action-controller/node_modules/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.8.0-58-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/himadri/node_modules/logitech-dual-action-controller/node_modules/node-hid
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by ChangkiSung** [comment]
sudo apt-get install libusb-1.0-0-dev

This solved the problem.
